### ISSUE TITLE
Link not working.

### ISSUE THREAD

**Issue by anwar6953** [sundaysenergy/www.supersimple.co#1]
Neither of the two links work, on the README (I think that's what it was).
Here's one link that fails. (I don't think the failure is on my end). I don't have HUGE interest in this project, I was just browsing around, and noticed.

This webpage is not available
The server at ruhoh.supersimple.com can't be found, because the DNS lookup failed.

http://ruhoh.supersimple.com/

**Comment by webmasterkai** [comment]
Thanks for the notice. We no longer support ruhoh website compiling.
